include:
  - ./composes/pg/compose.yaml
  - ./composes/nats/compose.yaml
  - ./composes/prometheus/compose.yaml
  - ./composes/grafana/compose.yaml

services:
  fastapi:
      image: scheduler-base:latest
      build:
        context: .
      container_name: fastapi
      command: uvicorn src.api.app:app --host 0.0.0.0 --port 8080
      ports:
        - "8080:8080"
      environment:
        - NATS_URL=nats://nats:4222
      networks:
        - default
        - monitoring
      depends_on:
        postgres:
          condition: service_healthy
        nats:
          condition: service_healthy

  taskiq_worker:
    image: scheduler-base:latest
    container_name: taskiq_worker
    command: taskiq worker src.infra.brokers.worker:broker
    environment:
      - NATS_URL=nats://nats:4222
    networks:
      - default
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy

networks:
  monitoring:
    driver: bridge